const foodJoongu = "/1_food/joongu_eunhang";
const foodSeogu = "/1_food/seogu_dunsan";
const foodYuseong = "/1_food/yuseong_bongmyeong";
const cafeJoongu = "/2_cafe/joongu_eunhang";
const cafeSeogu = "/2_cafe/seogu_dunsan";
const cafeYuseong = "/2_cafe/yuseong_bongmyeong";
const hotPlace = "/3_hotplace";

const generateImagePaths = (base, subFolder, imageCount) => {
  return Array.from({ length: imageCount }, (_, index) => {
    return `${base}/${subFolder}/${subFolder}${index + 1}.jpg`;
  });
};

let list = [
  //음식점
  //중구 음식점 시작 14개
  {
    id: "food_joongu_eunhang_a",
    title: "도쿄돈부리",
    images: generateImagePaths(foodJoongu, "a", 6),
    menu: ["가츠동", "규동", "돈까스"],
    categories: ["중구","일식", "밥","가성비"],
    description: "저렴한 가격에 즐길 수 있는 일식 집",
  },
  {
    id: "food_joongu_eunhang_b",
    title: "라스트춘선",
    images: generateImagePaths(foodJoongu, "b", 8),
    menu: ["한우 모츠나베", "정춘선 샤브나베", "육회 김밥"],
    categories: ["중구", "술", "힙해", "감성", "TOP9"],
    description: "한우 모츠나베(대창 전골)가 유명한 퓨전음식 술집",
  },
  {
    id: "food_joongu_eunhang_c",
    title: "무명",
    images: generateImagePaths(foodJoongu, "c", 7),
    menu: ["모듬숙성회", "백명란구이", "바지락술찜"],
    categories: ["중구", "일식", "해산물", "TOP9"],
    description: "숙성회와 전통주가 있는 대흥동 이자카야",
  },
  {
    id: "food_joongu_eunhang_d",
    title: "미도인",
    images: generateImagePaths(foodJoongu, "d", 7),
    menu: ["미도인 스테이크 덮밥", "미도인 가정식 스테이크", "가케소바"],
    categories: ["중구", "양식", "일식", "TOP9" ],
    description: "스테이크 덮밥이 유명한 밥집",
  },
  {
    id: "food_joongu_eunhang_e",
    title: "베리굿짬뽕돈까스",
    images: generateImagePaths(foodJoongu, "e", 6),
    menu: ["피자돈까스", "은행동왕갈비짬뽕", "순두부짬뽕"],
    categories: ["중구", "중식", "양식", "가성비"],
    description: "익숙한 짬뽕과 돈까스란 메뉴를 색다르게 만들어 파는 음식집",
  },
  {
    id: "food_joongu_eunhang_f",
    title: "보문산 호랭이",
    images: generateImagePaths(foodJoongu, "f", 5),
    menu: ["조개파스타", "청양베이컨파스타", "스테이크먹물리조또"],
    categories: ["중구", "양식", "힙해", "TOP9"],
    description: "파스타와 스테이크를 파는 깔끔한 양식집",
  },
  {
    id: "food_joongu_eunhang_g",
    title: "에그그",
    images: generateImagePaths(foodJoongu, "g", 6),
    menu: ["통베이컨파스타", "마그마오믈렛", "통베이컨 크림 리조또"],
    categories: ["중구", "양식", "밥", "TOP9"],
    description: "파스타와 오믈렛으로 유명한 양식집",
  },
  {
    id: "food_joongu_eunhang_h",
    title: "열개의 테이블",
    images: generateImagePaths(foodJoongu, "h", 5),
    menu: ["수란 통베이컨 크림 파스타", "치즈 플레이트", "진토닉"],
    categories: ["중구", "양식", "감성","술", "TOP9"],
    description: "양식과 술을 같이 즐길 수 있는 분위기 좋은 식당",
  },
  {
    id: "food_joongu_eunhang_i",
    title: "와요카레",
    images: generateImagePaths(foodJoongu, "i", 6),
    menu: ["스누피 카레"],
    categories: ["중구", "감성", "밥"],
    description: "지금은 망해서 없어져버렸지만, 한 때 스누피가 밥으로 그려져 나오는 카레로 유명했던 곳",
  },
  {
    id: "food_joongu_eunhang_j",
    title: "진로집",
    images: generateImagePaths(foodJoongu, "j", 6),
    menu: ["두부두루치기", "두부전", "두부김치전"],
    categories: ["중구", "술", "고기"],
    description: "두부에 미친 사장님의 손맛이 느껴지는 음식점",
  },
  {
    id: "food_joongu_eunhang_k",
    title: "청년다방",
    images: generateImagePaths(foodJoongu, "k", 5),
    menu: ["마라이징떡볶이", "차세대떡볶이", "불향차돌떡볶이"],
    categories: ["중구", "가성비"],
    description: "친숙하지만 가성비 좋은 그 떡볶이 집",
  },
  {
    id: "food_joongu_eunhang_l",
    title: "피그로",
    images: generateImagePaths(foodJoongu, "l", 8),
    menu: ["(점심)에그베네딕트", "(저녁)수비드항정살스테이크", "하이볼"],
    categories: ["중구", "양식", "술", "TOP9"],
    description: "고급스러운 양식과 와인이 좋은 곳이지만 엄마 카드를 쓰면 불효자가 되기 쉬운 곳",
  },
  {
    id: "food_joongu_eunhang_m",
    title: "홍콩구락부",
    images: generateImagePaths(foodJoongu, "m", 8),
    menu: ["동파육", "광동식 갈비 볶음밥", "코코넛 시리얼 새우"],
    categories: ["중구", "중식", "가성비", "해외여행", "TOP9"],
    description: "홍콩에 간듯한 느낌을 주는 식당",
  },
  {
    id: "food_joongu_eunhang_n",
    title: "희희초밥",
    images: generateImagePaths(foodJoongu, "n", 7),
    menu: ["희초밥", "희희초밥", "연어초밥"],
    categories: ["중구", "일식", "TOP9"],
    description: "먹을 때도 나갈 때도 희희 웃게되는 초밥집",
  },

  //서구 음식점 시작 14개
  {
    id: "food_seogu_dunsan_a",
    title: "DAON",
    images: generateImagePaths(foodSeogu, "a", 6),
    menu: ["다온 모듬꼬치", "마약옥수수", "왕 파닭꼬치"],
    categories: ["서구", "술", "TOP9"],
    description: "꼬치류가 레전드인 술집",
  },
  {
    id: "food_seogu_dunsan_b",
    title: "돈대장",
    images: generateImagePaths(foodSeogu, "b", 7),
    menu: ["돈대장삼겹한판", "목살한판", "쫄면순두부뚝배기"],
    categories: ["서구", "술","고기", "TOP9"],
    description: "고기가 구워져서 나와 손이 편한 고깃집",
  },
  {
    id: "food_seogu_dunsan_c",
    title: "모토이시",
    images: generateImagePaths(foodSeogu, "c", 7),
    menu: ["모츠나베", "일본식대창전골", "업진살"],
    categories: ["서구", "일식", "해외여행", "감성", "TOP9"],
    description: "일본식 와규(소고기)화로구이점",
  },
  {
    id: "food_seogu_dunsan_d",
    title: "몽상",
    images: generateImagePaths(foodSeogu, "d", 6),
    menu: ["사쿠라 직화 부타동", "우차돌 나베", "육회동"],
    categories: ["서구", "일식", "밥", "TOP9"],
    description: "혼밥하기 좋은 일본 밥집",
  },
  {
    id: "food_seogu_dunsan_e",
    title: "묵은정",
    images: generateImagePaths(foodSeogu, "e", 6),
    menu: ["묵은지 갈비찌개", "우순대국", "모듬순대"],
    categories: ["서구", "밥", "가성비"],
    description: "갈비와 김치의 아름다운 조화를 만들다",
  },
  {
    id: "food_seogu_dunsan_f",
    title: "백소정",
    images: generateImagePaths(foodSeogu, "f", 5),
    menu: ["돈카츠", "마제소바", "냉소바"],
    categories: ["서구", "일식", "TOP9"],
    description: "메뉴가 알찬 한상차림의 돈카츠 소바집",
  },
  {
    id: "food_seogu_dunsan_g",
    title: "셰셰",
    images: generateImagePaths(foodSeogu, "g", 7),
    menu: ["한우 대창나베", "얼큰 고기짬뽕탕", "유린기"],
    categories: ["서구", "중식", "해외여행", "감성"],
    description: "홍콩의 밤거리와 맛을 그대로 재현한 음식점",
  },
  {
    id: "food_seogu_dunsan_h",
    title: "소코아",
    images: generateImagePaths(foodSeogu, "h", 5),
    menu: ["소코아 카레", "에비카레", "소코연어동"],
    categories: ["서구", "일식","밥"],
    description: "카레와 밥을 한번 리필 할 수 있어 좋은 차분한 분위기의 카레 맛집",
  },
  {
    id: "food_seogu_dunsan_i",
    title: "연남",
    images: generateImagePaths(foodSeogu, "i", 7),
    menu: ["샤브전골", "육사시미", "하이볼"],
    categories: ["서구", "술","감성", "일식", "TOP9"],
    description: "한 쪽 벽에 영화가 나오는 조용하고 감성적인 분위기의 일식 술집",
  },
  {
    id: "food_seogu_dunsan_j",
    title: "용용선생",
    images: generateImagePaths(foodSeogu, "j", 9),
    menu: ["화산마라전골", "홍콩덕냉채", "우육탕"],
    categories: ["서구", "술", "중식", "해외여행","감성","힙해", "TOP9"],
    description: "화산처럼 생긴 마라전골이 유명한 홍콩 분위기의 맛집",
  },
  {
    id: "food_seogu_dunsan_k",
    title: "청사광장",
    images: generateImagePaths(foodSeogu, "k", 7),
    menu: ["생목살 숯불 바베큐&샐러드", "나가사키 짬뽕탕", "깐풍 칠리새우"],
    categories: ["서구", "감성", "술","고기", "TOP9"],
    description: "야외테라스에서 숯불 바베큐 구이 먹어볼래?",
  },
  {
    id: "food_seogu_dunsan_l",
    title: "청청",
    images: generateImagePaths(foodSeogu, "l", 8),
    menu: ["버터우동", "차돌박이 들기름파스타", "치즈플래터"],
    categories: ["서구", "감성","힙해","술"],
    description: "LP 음악이 흐르는 감성적인 Dining PUB",
  },
  {
    id: "food_seogu_dunsan_m",
    title: "택이네 조개전골",
    images: generateImagePaths(foodSeogu, "m", 5),
    menu: ["조개전골", "조개칼국수", "해물삼함"],
    categories: ["서구", "한식", "술","해산물"],
    description: "싱싱한 조개가 연안 부두의 배처럼 입안에서 날뛴다",
  },
  {
    id: "food_seogu_dunsan_n",
    title: "향연돈",
    images: generateImagePaths(foodSeogu, "n", 6),
    menu: ["(모두 무한리필)대패삼겹", "활전복", "샐러드바"],
    categories: ["서구", "술", "해산물", "고기", "TOP9"],
    description: "고기와 해산물이 무한리필되는 사장님이 걱정되는 곳",
  },

  //유성 음식점 시작 14개
  {
    id: "food_yuseong_bongmyeong_a",
    title: "1984 술마시는 작업실",
    images: generateImagePaths(foodYuseong, "a", 6),
    menu: ["봉골레 파스타", "BBQ플래터", "감바스"],
    categories: ["유성", "양식","술","감성","힙해", "TOP9"],
    description: "고급스러운 인테리어에 버금가는 맛의 양식과 맥주가 있는 곳",
  },
  {
    id: "food_yuseong_bongmyeong_b",
    title: "거리꼬치구이",
    images: generateImagePaths(foodYuseong, "b", 9),
    menu: ["꼬치구이"],
    categories: ["유성", "술","고기", "TOP9"],
    description: "꼬치꼬치 묻지 않아도 직접 구워 맛있어 보이는 꼬치집",
  },
  {
    id: "food_yuseong_bongmyeong_c",
    title: "고치소사마",
    images: generateImagePaths(foodYuseong, "c", 6),
    menu: ["일본식 카레라이스", "모듬초밥", "생연어 회덮밥"],
    categories: ["유성", "일식","가성비","밥"],
    description: "일본현지 방식의 카레를 한국인 입맛에 맞췄다",
  },
  {
    id: "food_yuseong_bongmyeong_d",
    title: "구주",
    images: generateImagePaths(foodYuseong, "d", 3),
    menu: ["진격의 구주도넛(샤브샤브)", "갈비양념구이", "바지락술찜"],
    categories: ["유성", "일식", "술"],
    description: "샤브샤브가 도넛 모양으로 나오는 신기한 곳",
  },
  {
    id: "food_yuseong_bongmyeong_e",
    title: "금별맥주",
    images: generateImagePaths(foodYuseong, "e", 4),
    menu: ["백합조개 버터술찜", "사모님! 감바스", "뚝배기 골뱅이 메밀 비빔국수"],
    categories: ["유성", "술","감성","힙해"],
    description: "사모님! 감바스는 대체 무슨 맛일까?",
  },
  {
    id: "food_yuseong_bongmyeong_f",
    title: "모큐요비",
    images: generateImagePaths(foodYuseong, "f", 5),
    menu: ["스테이크 덮밥", "연어 덮밥", "대패 덮밥"],
    categories: ["유성", "일식","밥","감성", "TOP9"],
    description: "일본식 한상차림, 호불호 없는 덮밥 판매중",
  },
  {
    id: "food_yuseong_bongmyeong_g",
    title: "묘한식당",
    images: generateImagePaths(foodYuseong, "g", 6),
    menu: ["해장파스타", "치킨로제빠네파스타", "아롱사태수육", "새우나쵸"],
    categories: ["유성", "술","해산물","고기", "양식", "TOP9"],
    description: "술 마시러가서 파스타 먹고 해장하기",
  },
  {
    id: "food_yuseong_bongmyeong_h",
    title: "박봉명생갈비",
    images: generateImagePaths(foodYuseong, "h", 7),
    menu: ["생갈비소금구이"],
    categories: ["유성", "술","고기", "TOP9"],
    description: "'간판에 메뉴 하나만 걸어놓는 음식점을 조심해...'",
  },
  {
    id: "food_yuseong_bongmyeong_i",
    title: "오사카데스",
    images: generateImagePaths(foodYuseong, "i", 5),
    menu: ["나폴리탄 스파게티", "오꼬노미야끼", "3종 모듬회"],
    categories: ["유성", "해외여행","일식","술","힙해", "해산물", "TOP9"],
    description: "일본 현지 느낌을 느낄 수 있는 트랜디한 술집",
  },
  {
    id: "food_yuseong_bongmyeong_j",
    title: "진원소우",
    images: generateImagePaths(foodYuseong, "j", 5),
    menu: ["소고기 무한리필", "소는 한자로", "소우"],
    categories: ["유성", "술", "고기", "TOP9"],
    description: "'나 어제 소고기 먹었어!'라고 말하기 좋은 곳",
  },
  {
    id: "food_yuseong_bongmyeong_k",
    title: "파도수산",
    images: generateImagePaths(foodYuseong, "k", 5),
    menu: ["파도해물라면", "3종모듬회", "해물짬뽕탕"],
    categories: ["유성", "술","해산물"],
    description: "해물에 라면에 소주 그리고 물회",
  },
  {
    id: "food_yuseong_bongmyeong_l",
    title: "서울갈비집",
    images: generateImagePaths(foodYuseong, "l", 5),
    menu: ["수제양념갈비", "생갈비", "매운돼지꼬리"],
    categories: ["유성", "술", "고기"],
    description: "최고급 참숯을 사용하고 천연과일양념으로 질 좋은 고기를 제공하는 갈비집",
  },
  {
    id: "food_yuseong_bongmyeong_m",
    title: "호맥",
    images: generateImagePaths(foodYuseong, "m", 5),
    menu: ["앙설탕 호떡", "초코 마카다미아 호떡", "(생맥주)두근두근 IPA"],
    categories: ["유성", "술", "힙해", "TOP9"],
    description: "호떡 맥주의 신선한 조합! 무알콜 음료도 있음",
  },
  {
    id: "food_yuseong_bongmyeong_n",
    title: "호연재",
    images: generateImagePaths(foodYuseong, "n", 5),
    menu: ["계룡산 모둠 한판", "해물 순두부 찌개", "하이볼 100잔 무한리필"],
    categories: ["유성", "술", "고기", "해산물", "TOP9"],
    description: "숯불 닭구이부터 해물순두부찌개까지 맥주에 곁들여 먹을 수 있는 곳",
  },

  //카페
  //중구 카페 시작 14개
  {
    id: "cafe_joongu_eunhang_a",
    title: "디버전",
    images: generateImagePaths(cafeJoongu, "a", 6),
    menu: ["슈크림라떼", "달고나라떼", "코로플"],
    categories: ["중구", "힙해","모던한","TOP9"],
    description: "건물 한 부분이 잘린듯한 독특한 외관, 카페&칵테일&맥주",
  },
  {
    id: "cafe_joongu_eunhang_b",
    title: "땡큐베리머치",
    images: generateImagePaths(cafeJoongu, "b", 7),
    menu: ["아메리카노", "얼그레이쇼콜라", "버터스카치카라멜케이크"],
    categories: ["중구", "가성비","TOP9"],
    description: "프리미엄 수제 디저트샵, 다양한 종류의 쿠키와 케이크까지 ",
  },
  {
    id: "cafe_joongu_eunhang_c",
    title: "라이커블",
    images: generateImagePaths(cafeJoongu, "c", 5),
    menu: ["단호박샌드위치", "청포도케일주스", "수제바닐라라떼"],
    categories: ["중구", "가성비", "식물"],
    description: "식물을 함께 판매하는 플렌테리어 카페",
  },
  {
    id: "cafe_joongu_eunhang_d",
    title: "바이라니",
    images: generateImagePaths(cafeJoongu, "d", 7),
    menu: ["바닐라빈라떼", "크로플", "수박주스"],
    categories: ["중구", "아담한","TOP9"],
    description: "편안한 분위기의 브런치 카페",
  },
  {
    id: "cafe_joongu_eunhang_e",
    title: "성심당",
    images: generateImagePaths(cafeJoongu, "e", 8),
    menu: ["튀김소보로", "보문산메아리", "성심순크림빵"],
    categories: ["중구", "가성비", "빵","TOP9"],
    description: "1956년 부터 이어진 대전 대표 빵집",
  },
  {
    id: "cafe_joongu_eunhang_f",
    title: "오멜라스",
    images: generateImagePaths(cafeJoongu, "f", 5),
    menu: ["", "", ""],
    categories: ["중구", "식물"],
    description: "",
  },
  {
    id: "cafe_joongu_eunhang_g",
    title: "오시우커피",
    images: generateImagePaths(cafeJoongu, "g", 6),
    menu: ["오시우망고", "오시우플로트", "흑임자아이스크림"],
    categories: ["중구", "모던한","TOP9"],
    description: "다양한 종류의 아이스크림 커피",
  },
  {
    id: "cafe_joongu_eunhang_h",
    title: "오프위고",
    images: generateImagePaths(cafeJoongu, "h", 6),
    menu: ["트리플베리에이드", "맘모스바스크치즈케이크", "망고우유케이크"],
    categories: ["중구", "식물","TOP9"],
    description: "수제청으로 만든 에이드와 수제케이크를 만날수 있는 곳",
  },
  {
    id: "cafe_joongu_eunhang_i",
    title: "올드하우스",
    images: generateImagePaths(cafeJoongu, "i", 6),
    menu: ["하우스커피", "말차슈페너", "발로나초코슈페너"],
    categories: ["중구", "모던한","TOP9"],
    description: "오래된 건물의 모던한 인테리어가 돋보이는 곳",
  },
  {
    id: "cafe_joongu_eunhang_j",
    title: "원더풀",
    images: generateImagePaths(cafeJoongu, "j", 4),
    menu: ["딸기크림라떼", "애플망고패션후르츠에이드", "레몬에이드"],
    categories: ["중구", "힙해","TOP9"],
    description: "미디어아트로 이색적인 카페",
  },
  {
    id: "cafe_joongu_eunhang_k",
    title: "카페디아로마",
    images: generateImagePaths(cafeJoongu, "k", 7),
    menu: ["아이스크림와플", "레인보우와플", "카페크림라떼"],
    categories: ["중구", "모던한","TOP9"],
    description: "매일 직접 만드는 수제 와플맛집",
  },
  {
    id: "cafe_joongu_eunhang_l",
    title: "코페부쉬",
    images: generateImagePaths(cafeJoongu, "l", 5),
    menu: ["소금크림커피", "라즈베리 소르베"],
    categories: ["중구", "식물"],
    description: "꽃과 식물, 커피와 디저트가 있는 카페",
  },
  {
    id: "cafe_joongu_eunhang_m",
    title: "크리켓사운드",
    images: generateImagePaths(cafeJoongu, "m", 6),
    menu: ["시나몬크림라떼", "소금커피", "크림라떼"],
    categories: ["중구", "우드톤"],
    description: "우드톤의 애견 동반 카페",
  },
  {
    id: "cafe_joongu_eunhang_n",
    title: "홀리우드",
    images: generateImagePaths(cafeJoongu, "n", 4),
    menu: ["", "", ""],
    categories: ["중구", "우드톤","술도 파는"],
    description: "",
  },

  //서구 카페 시작 16개
  {
    id: "cafe_seogu_eunhang_a",
    title: "SSAW",
    images: generateImagePaths(cafeSeogu, "a", 6),
    menu: ["바닐라빈라떼", "플랫화이트", "콜드브루아인슈페너"],
    categories: ["서구", "모던한", "깔끔한","TOP9"],
    description: "깔끔하고 감각적인 분위기인 카페",
  },
  {
    id: "cafe_seogu_eunhang_b",
    title: "게리동서비스",
    images: generateImagePaths(cafeSeogu, "b", 8),
    menu: ["커널라떼", "까망베르크루와상", "플랫 화이트"],
    categories: ["서구", "우드톤", "힙해","TOP9"],
    description: "우드톤의 LP 카페",
  },
  {
    id: "cafe_seogu_eunhang_c",
    title: "랑데자뷰",
    images: generateImagePaths(cafeSeogu, "c", 7),
    menu: ["바닐라라떼", "밀크티", "자몽주스"],
    categories: ["서구", "힙해", "여행느낌","TOP9"],
    description: "제주 자연의 느낌을 담은 감성 카페",
  },
  {
    id: "cafe_seogu_eunhang_d",
    title: "리셉션",
    images: generateImagePaths(cafeSeogu, "d", 4),
    menu: ["잠봉뵈르", "크루와상샌드위치", "크렘당쥬"],
    categories: ["서구", "우드톤"],
    description: "빈티지스러우면서 트렌디한 카페",
  },
  {
    id: "cafe_seogu_eunhang_e",
    title: "블레스롤",
    images: generateImagePaths(cafeSeogu, "e", 4),
    menu: ["오더쿠크림", "빠더쿠크림", "초코초코블레치노"],
    categories: ["서구", "넓은"],
    description: "고급스러운 분위기의 감성 카페",
  },
  {
    id: "cafe_seogu_eunhang_f",
    title: "숍비피",
    images: generateImagePaths(cafeSeogu, "f", 5),
    menu: ["프렌치 토스트", "너츠라떼", "바나나 머쉬룸 밀크티"],
    categories: ["서구", "모던한"],
    description: "트리뷰가 좋은 감성 카페",
  },
  {
    id: "cafe_seogu_eunhang_g",
    title: "슬리피타운",
    images: generateImagePaths(cafeSeogu, "g", 8),
    menu: ["슬리피라떼", "아이스크림 샌드위치", "마리아쥬 웨딩 임페리얼 티"],
    categories: ["서구", "우드톤","TOP9"],
    description: "창 풍경과 대화하기 좋은 카페",
  },
  {
    id: "cafe_seogu_eunhang_h",
    title: "앤댄",
    images: generateImagePaths(cafeSeogu, "h", 6),
    menu: ["레몬글라세 마들렌", "플레인 휘낭시에", "바닐라 까눌레"],
    categories: ["서구", "아담한","TOP9"],
    description: "휘낭시에, 마들렌 맛집",
  },
  {
    id: "cafe_seogu_eunhang_i",
    title: "에어온",
    images: generateImagePaths(cafeSeogu, "i", 6),
    menu: ["카페라떼", "생복숭아에이드", "소금 바닐라 마카롱"],
    categories: ["서구", "식물","TOP9"],
    description: "엔틱한 분위기와 직접 로스팅한 커피를 만나볼수 있는 곳",
  },
  {
    id: "cafe_seogu_eunhang_j",
    title: "요거틀리",
    images: generateImagePaths(cafeSeogu, "j", 6),
    menu: ["브라운 포도", "바질토마토", "플레인 그릭 요거트"],
    categories: ["서구", "아담한"],
    description: "매일 아침 직접 배합,발효,숙성하는 그릭요거트 맛집",
  },
  {
    id: "cafe_seogu_eunhang_k",
    title: "에이치에이치라운지",
    images: generateImagePaths(cafeSeogu, "k", 8),
    menu: ["SPACE", "WOOD", "FOREST"],
    categories: ["중구", "힙해", "술도 파는","TOP9"],
    description: "커피와 펍이 함께하는 라운지 펍",
  },
  {
    id: "cafe_seogu_eunhang_l",
    title: "크러쉬온드",
    images: generateImagePaths(cafeSeogu, "l", 5),
    menu: ["아메리카노(블렌딩)", "크렘 드", "흑임자 바스크 치즈케이크"],
    categories: ["서구", "힙해"],
    description: "모던하고 미니멀한 인테리어 카페",
  },
  {
    id: "cafe_seogu_eunhang_m",
    title: "티켓부스",
    images: generateImagePaths(cafeSeogu, "m", 4),
    menu: ["", "", ""],
    categories: ["서구", "힙해"],
    description: "",
  },
  {
    id: "cafe_seogu_eunhang_n",
    title: "프랭크커핀바",
    images: generateImagePaths(cafeSeogu, "n", 8),
    menu: ["그라니따", "로마노", "바치오"],
    categories: ["서구", "힙해", "여행느낌","TOP9"],
    description: "유럽풍 분위기의 카페",
  },
  {
    id: "cafe_seogu_eunhang_o",
    title: "피닉",
    images: generateImagePaths(cafeSeogu, "o", 8),
    menu: ["레인보우 리타", "90's 파르페", "옐로우 하와이 스무디"],
    categories: ["서구", "힙해","TOP9"],
    description: "도심속 휴양지 분위기의 루프탑 카페",
  },
  {
    id: "cafe_seogu_eunhang_p",
    title: "홀리크로스",
    images: generateImagePaths(cafeSeogu, "p", 6),
    menu: ["홀크와플 킹", "홀크 수제버거", "순수 카카오라떼"],
    categories: ["서구", "식물"],
    description: "",
  },

  //유성 카페 시작 12개
  {
    id: "cafe_yuseong_eunhang_a",
    title: "레코드카페도넛",
    images: generateImagePaths(cafeYuseong, "a", 7),
    menu: ["filtered black", "einspänner", "토마토 소르베"],
    categories: ["유성구", "힙해", "아담한","TOP9"],
    description: "LP샵과 커피를 만나볼수 있는 곳",
  },
  {
    id: "cafe_yuseong_eunhang_b",
    title: "루즈",
    images: generateImagePaths(cafeYuseong, "b", 5),
    menu: ["구름커피", "크로플", "체리 에이드"],
    categories: ["유성구", "식물", "깔끔한"],
    description: "독특한 인테리어가 돋보이는 곳",
  },
  {
    id: "cafe_yuseong_eunhang_c",
    title: "루티나",
    images: generateImagePaths(cafeYuseong, "c", 8),
    menu: ["아인슈페너", "수제 크림 모카", "망고렌지"],
    categories: ["유성구", "모던한", "넓은","TOP9"],
    description: "모던한 인테리어와 넓은 실내의 카페",
  },
  {
    id: "cafe_yuseong_eunhang_d",
    title: "리케리케",
    images: generateImagePaths(cafeYuseong, "d", 9),
    menu: ["에스프레소", "리케리얼주스", "케모마일 스파클링 에이드"],
    categories: ["유성구", "모던한", "넓은","TOP9"],
    description: "낮엔 카페, 밤엔 분위기 있는 펍을 운영하는 곳",
  },
  {
    id: "cafe_yuseong_eunhang_e",
    title: "쎄시마몽드",
    images: generateImagePaths(cafeYuseong, "e", 8),
    menu: ["땅콩 아몬드 크림 라떼", "스몰 라떼", "멋쟁이 토마토"],
    categories: ["유성구", "힙해", "아담한","TOP9"],
    description: "힙한 인테리어와 레트로 무드의 카페",
  },
  {
    id: "cafe_yuseong_eunhang_f",
    title: "아케이드커피",
    images: generateImagePaths(cafeYuseong, "f", 8),
    menu: ["딥블랙", "밀크티", "얼그레이 크림라떼"],
    categories: ["유성구", "넓은", "모던한","TOP9"],
    description: "독특한 인테리어와 넓은 실내의 카페",
  },
  {
    id: "cafe_yuseong_eunhang_g",
    title: "에이트",
    images: generateImagePaths(cafeYuseong, "g", 7),
    menu: ["아몬드 크림 라떼", "에이트 로투스 라떼", "소금라떼"],
    categories: ["유성구", "넓은", "힙해","TOP9"],
    description: "넓은 공간과 모던한 인테리어가 돋보이는 베이커리 카페",
  },
  {
    id: "cafe_yuseong_eunhang_h",
    title: "읍천리382",
    images: generateImagePaths(cafeYuseong, "h", 6),
    menu: ["약과스무디", "불고기샌드위치", "딸기밭라떼"],
    categories: ["유성구", "가성비","힙해","TOP9"],
    description: "도심 속 레트로 감성 카페",
  },
  {
    id: "cafe_yuseong_eunhang_i",
    title: "커피인터뷰",
    images: generateImagePaths(cafeYuseong, "i", 8),
    menu: ["코코파인", "자두에이드", "땅콩슈페너"],
    categories: ["유성구", "식물","여행느낌","넓은","TOP9"],
    description: "동남아감성의 도심 속 카페",
  },
  {
    id: "cafe_yuseong_eunhang_j",
    title: "퍼플데이",
    images: generateImagePaths(cafeYuseong, "j", 6),
    menu: ["", "", ""],
    categories: ["유성구", "힙한", "가성비", "아담한"],
    description: "",
  },
  {
    id: "cafe_yuseong_eunhang_k",
    title: "하루팡",
    images: generateImagePaths(cafeYuseong, "k", 7),
    menu: ["야끼소바빵", "메론빵", "소금빵"],
    categories: ["유성구", "모던한", "빵"],
    description: "일본식 베이커리 빵집",
  },
  {
    id: "cafe_yuseong_eunhang_l",
    title: "하이테이블",
    images: generateImagePaths(cafeYuseong, "l", 7),
    menu: ["블루베리라떼", "딸기라떼", "코코넛 스무디"],
    categories: ["유성구", "넓은", "빵","TOP9"],
    description: "트렌디한 인테리어와 24시간 베이커리 카페",
  },

  //핫플레이스는 메뉴 대신 유명한 거를 몇 개 적어야 할듯. famous로 해야겠다.
  //핫플레이스 시작 14개
  {
    id: "hotplace_a",
    title: "금강 로하스 공원",
    images: generateImagePaths(hotPlace, "a", 1),
    famous: ["", "", ""],
    categories: ["대덕구", "공원", "자연", "야외"],
    description: "대청댐에 있는 자연 생태 공연",
  },
  {
    id: "hotplace_b",
    title: "대동 하늘공원",
    images: generateImagePaths(hotPlace, "b", 8),
    famous: ["", "", ""],
    categories: ["동구", "공원", "자연", "야외","TOP9"],
    description: "레트로 분위기의 풍경과 야경",
  },
  {
    id: "hotplace_c",
    title: "둔산 들의공원",
    images: generateImagePaths(hotPlace, "c", 4),
    famous: ["", "", ""],
    categories: ["서구", "공원", "자연", "야외","TOP9"],
    description: "도심속 자연을 느낄수 있는 공원",
  },
  {
    id: "hotplace_d",
    title: "대전 시민천문대",
    images: generateImagePaths(hotPlace, "d", 6),
    famous: ["", "", ""],
    categories: ["유성구", "자연", "실내", "야경","TOP9" ],
    description: "대전시에 건립한 천문대로 시민들이 자유롭게 관측할수 있는 곳",
  },
  {
    id: "hotplace_e",
    title: "식장산 전망대",
    images: generateImagePaths(hotPlace, "e", 5),
    famous: ["", "", ""],
    categories: ["동구", "야외", "야경"],
    description: "대전을 한눈에 볼수 있는 전망대",
  },
  {
    id: "hotplace_f",
    title: "대전 신세계 갤러리",
    images: generateImagePaths(hotPlace, "f", 7),
    famous: ["", "", ""],
    categories: ["유성구", "실내", "예술","TOP9"],
    description: "트렌디하고 색다른 작은 전시를 볼수 있는 곳",
  },
  {
    id: "hotplace_g",
    title: "엑스포 시민 광장",
    images: generateImagePaths(hotPlace, "g", 9),
    famous: ["", "", ""],
    categories: ["서구", "실내", "대피","TOP9"],
    description: "문화생활, 레저 스포츠, 행사 등 기간마다 다양한 행사가 진행되는곳",
  },
  {
    id: "hotplace_h",
    title: "엑스포 아쿠아리움",
    images: generateImagePaths(hotPlace, "h", 4),
    famous: ["", "", ""],
    categories: ["유성구", "대피", "실내"],
    description: "신화 속 바다를 배경으로한 아쿠아리움",
  },
  {
    id: "hotplace_i",
    title: "옛터민속박물관",
    images: generateImagePaths(hotPlace, "i", 7), 
    famous: ["", "", ""],
    categories: ["동구", "대피", "실내","TOP9"],
    description: "사립 박물관으로 식당, 찻집까지 이용할수 있다.",
  },
  {
    id: "hotplace_j",
    title: "오월드",
    images: generateImagePaths(hotPlace, "j", 7),
    famous: ["", "", ""],
    categories: ["중구", "야외", "자연","TOP9"],
    description: "동물원, 플라워랜드, 야간개장으로 가족과 연인들이 방문하기 좋은곳",
  },
  {
    id: "hotplace_k",
    title: "대전 월드컵경기장",
    images: generateImagePaths(hotPlace, "k", 7),
    famous: ["", "", ""],
    categories: ["유성구", "야외", "스포츠","TOP9"],
    description: "대전하나시티즌의 홈 경기장.",
  },
  {
    id: "hotplace_l",
    title: "이응노미술관",
    images: generateImagePaths(hotPlace, "l", 8),
    famous: ["", "", ""],
    categories: ["서구", "실내", "예술","TOP9"],
    description: " 2007년 5월 개관하여 세계 유일의 고암 연구센터로서 전시, 연구, 출판, 교육 등 복합적인 기능을 수행",
  },
  {
    id: "hotplace_m",
    title: "한화이글스 야구장",
    images: generateImagePaths(hotPlace, "m", 6),
    famous: ["", "", ""],
    categories: ["중구", "야외", "스포츠"],
    description: "대전 한화이글스팀의 홈 경기장",
  },
  {
    id: "hotplace_n",
    title: "헤레디움",
    images: generateImagePaths(hotPlace, "n", 7),
    famous: ["", "", ""],
    categories: ["동구", "예술", "실내", "대피"],
    description: "1922년  일제강점기때 지어져 현재는 문화예술공간으로 이용중",
  },

];

export const data = {
  foodJoongu,
  foodSeogu,
  foodYuseong,
  cafeJoongu,
  cafeSeogu,
  cafeYuseong,
  hotPlace,
  generateImagePaths,
  list,
};
